# Generated by Django 3.2.7 on 2021-10-30 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scials',
            new_name='Socials',
        ),
    ]
