# Generated by Django 3.2.7 on 2021-10-30 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0002_rename_scials_socials'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Socials',
            new_name='Social',
        ),
    ]
