# Generated by Django 3.2.7 on 2021-10-30 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0003_rename_socials_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='icon',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
